version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-weather
    restart: always
    ports:
      - '5435:5432'
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-weather
    restart: always
    depends_on:
      - postgres
    ports:
      - '5050:80'            
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
  weather:
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    env_file:
      - .env
  subscription:
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
volumes:
  pgdata:
  pgadmin_data: