version: '3.8'

services:
  postgres-test:
    image: postgres:15
    container_name: pg-weather-test
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres-test
      POSTGRES_PASSWORD: postgres-test
      POSTGRES_DB: test-db
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    env_file:
      - .env.test.local
  redis-test:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
volumes:
  pgdata_test: