name: Test (Integration Tests)

on:
  [push, pull_request]
jobs:
  int-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Copy local env file
        run: cp .env.test.example .env.test.local

      - name: Start mock server
        run: pnpm start:test weather

      - name: Run tests
        run: pnpm test:int

